<a href="https://colab.research.google.com/github/suyogy1-bot/Numpy_Pandas/blob/main/Pandas_class7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [1]:
import pandas as pd
# Dataset 1: Product details
df1 = pd.DataFrame({
    'ProductID': [101,102,103],
    'ProductName': ['Pen', 'Notebook', 'Marker'],
    'Price': [10, 50, 30]})


# Dataset 2: More products (same columns as df1 → good for vertical stacking)

df2 = pd.DataFrame({
    'ProductID': [104,105,106],
    'ProductName': ['Pencil', 'Eraser', 'Ruler'],
    'Price': [5, 20, 15]})

# Dataset 3: Additional info (different columns → good for horizontal stacking)

df3 = pd.DataFrame({
    'Stock': [100, 50, 75],
    'Rating': [4.5, 4.7, 4.8]
})

print(f"DF1 {df1}")
print(f"DF2 {df2}")
print(f"DF3 {df3}")

DF1    ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
DF2    ProductID ProductName  Price
0        104      Pencil      5
1        105      Eraser     20
2        106       Ruler     15
DF3    Stock  Rating
0    100     4.5
1     50     4.7
2     75     4.8

In [6]:
#1. Vertical stacking (axis = 0)

# By default concat does vertical stacking

vertical_stacking = pd.concat([df1, df2])
print(f"Vertical Stacking:\n{vertical_stacking}")

Vertical Stacking:
   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
0        104      Pencil      5
1        105      Eraser     20
2        106       Ruler     15

In [4]:
# To change index values

vertical_stacking = pd.concat([df1, df2], axis=0, ignore_index=True)
print(f"Vertical Stacking:\n{vertical_stacking}")

Vertical Stacking:
   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser     20
5        106       Ruler     15

In [7]:
#2. Horizontal Stacking (axis = 1)

horizontal_stacking = pd.concat([df1, df3], axis=1)
print(f"Horizontal Stacking:\n{horizontal_stacking}")

Horizontal Stacking:
   ProductID ProductName  Price  Stock  Rating
0        101         Pen     10    100     4.5
1        102    Notebook     50     50     4.7
2        103      Marker     30     75     4.8

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [14]:
# We have to concat df1 and df2 rows wise

Product = pd.concat([df1, df2], ignore_index=True)
print(f"Produce Df:\n{Product}")

Sales = pd.DataFrame({
    'ProductID': [101, 103, 105],
    'Sales': [1000, 800, 1200]
})

print(f"Sales Df:\n{Sales}")

Revenue = pd.DataFrame({
    'ProductID': [101, 102, 103],
    'Revenue': [2000, 1500, 2500]})

print(f"Revenue Df:\n{Revenue}")

Produce Df:
   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser     20
5        106       Ruler     15
Sales Df:
   ProductID  Sales
0        101   1000
1        103    800
2        105   1200
Revenue Df:
   ProductID  Revenue
0        101     2000
1        102     1500
2        103     2500

In [15]:
#1. Inner Join (Done Dataframes ke beech only matching ProductId)

pd.merge(Product,Sales, how='inner')

   ProductID ProductName  Price  Sales
0        101         Pen     10   1000
1        103      Marker     30    800
2        105      Eraser     20   1200

In [16]:
#2. Left Join (Take left full table and only common element of Right Table)

pd.merge(Product,Sales, how='left')

   ProductID ProductName  Price   Sales
0        101         Pen     10  1000.0
1        102    Notebook     50     NaN
2        103      Marker     30   800.0
3        104      Pencil      5     NaN
4        105      Eraser     20  1200.0
5        106       Ruler     15     NaN

In [17]:
#3. Right Join (Take Right Table full and Left Table only common elements)

pd.merge(Product, Sales, how='right')

   ProductID ProductName  Price  Sales
0        101         Pen     10   1000
1        103      Marker     30    800
2        105      Eraser     20   1200

In [18]:
#4. Outer join (Everthing, even unmatched)

outer = pd.merge(Product, Sales, how='outer')
print(f"Outer Join:\n{outer}")

Outer Join:
   ProductID ProductName  Price   Sales
0        101         Pen     10  1000.0
1        102    Notebook     50     NaN
2        103      Marker     30   800.0
3        104      Pencil      5     NaN
4        105      Eraser     20  1200.0
5        106       Ruler     15     NaN

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [29]:
#1. Join stock information to product

Sales = pd.DataFrame({
    'UnitsSold': [101, 103, 105, 200, 300]},
    index = [101, 102, 103, 104, 105]
)

print(f"Sales:\n{Sales}")

Sales:
     UnitsSold
101        101
102        103
103        105
104        200
105        300

In [30]:
p_indexed = Product.set_index('ProductID')
joined = p_indexed.join(Sales)
print(f"Joined:\n{joined}")

Joined:
          ProductName  Price  UnitsSold
ProductID
101               Pen     10      101.0
102          Notebook     50      103.0
103            Marker     30      105.0
104            Pencil      5      200.0
105            Eraser     20      300.0
106             Ruler     15        NaN

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [ ]:

# 1. Create three DataFrames: Products, Sales, and Revenue

# 2. Concatenate them vertically and horizontally
# Write your code here

# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
# Write your code here

# 4. Join Products with Sales based on index or a key
# Write your code here

# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps
# Write your code here

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.