<a href="https://colab.research.google.com/github/suyogy1-bot/Numpy_Pandas/blob/main/pandas_class4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [6]:
import pandas as pd

a = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'Score': [85, 90, 78, 92, 88]
}

b = pd.DataFrame(a)
b

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     78
3    David   40     92
4      Eve   45     88

In [2]:
#1. Select single column

b[b['Age'] > 27]

      Name  Age  Score
1      Bob   30     90
2  Charlie   35     78
3    David   40     92
4      Eve   45     88

In [4]:
#2. Selecting single column score > 85

b[b['Score'] > 85]

    Name  Age  Score
1    Bob   30     90
3  David   40     92
4    Eve   45     88

In [13]:
#3. Multiple Conditions (AND): Age > 27 AND Score > 90

b[(b['Age'] > 27) & (b['Score'] > 90)]

    Name  Age  Score
3  David   40     92

In [15]:
#4. Multiple Conditions (OR): Age >= 40 or Score > 90

b[(b['Age'] >= 40) | (b['Score'] > 90)]

    Name  Age  Score
3  David   40     92
4    Eve   45     88

In [16]:
#5. Multiple Conditions (Not): Score not > 85

b[~(b['Score'] > 85)]

      Name  Age  Score
0    Alice   25     85
2  Charlie   35     78

In [17]:
#6. Age > 22 and Score > 80

b[(b['Age'] > 22) & (b['Score'] > 80)]

    Name  Age  Score
0  Alice   25     85
1    Bob   30     90
3  David   40     92
4    Eve   45     88

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [20]:
#1. Age > 30 and Score > 85

b[(b['Age'] > 30) & (b['Score'] > 85)]

    Name  Age  Score
3  David   40     92
4    Eve   45     88

In [21]:
#2. Age < 35 or Score >= 90

b[(b['Age']> 35) | (b['Score'] > 90)]

    Name  Age  Score
3  David   40     92
4    Eve   45     88

In [25]:
#3. Age between 25 and 35 (both inclusive) using not operator

b[~(b['Age'] <= 25) & ~(b['Age'] >= 35)]

  Name  Age  Score
1  Bob   30     90

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [29]:
#1. Simple Query : Age > 25

print(b.query("Age > 25"))

      Name  Age  Score
1      Bob   30     90
2  Charlie   35     78
3    David   40     92
4      Eve   45     88

In [28]:
#2. Mutliple Conditions using query

print(b.query("Age > 25 & Score > 90"))

    Name  Age  Score
3  David   40     92

In [30]:
print(b.query("Age > 30 | Score > 90"))

      Name  Age  Score
2  Charlie   35     78
3    David   40     92
4      Eve   45     88

In [33]:
b

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     78
3    David   40     92
4      Eve   45     88

In [35]:
print(b.query("~(Age < 25) & ~(Age > 35)"))

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     78

In [38]:
#3. Threshold (@)

score = 90 #Variable
b.query("Score > @score") # Score > 90

    Name  Age  Score
3  David   40     92

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [39]:
#1. Convert name to lowercase()

print(b['Name'].str.lower()) # str -> converts into string

0      alice
1        bob
2    charlie
3      david
4        eve
Name: Name, dtype: object

In [40]:
#2. Convert name to uppercase()

print(b['Name'].str.upper())

0      ALICE
1        BOB
2    CHARLIE
3      DAVID
4        EVE
Name: Name, dtype: object

In [44]:
#3. title() -> Capitalize first letter

print(b['Name'].str.title())

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object

In [41]:
#3. Contains()

print(b['Name'].str.contains('Bob'))

0    False
1     True
2    False
3    False
4    False
Name: Name, dtype: bool

In [42]:
#4. Replace()

print(b['Name'].str.replace('Bob', 'Bobby'))

0      Alice
1      Bobby
2    Charlie
3      David
4        Eve
Name: Name, dtype: object

In [52]:
#5. startswith()

print(b['Name'])
print(b['Name'].str.startswith('a')) # Gives False
print(b['Name'].str.startswith('A'))

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object
0    False
1    False
2    False
3    False
4    False
Name: Name, dtype: bool
0     True
1    False
2    False
3    False
4    False
Name: Name, dtype: bool

In [50]:
#6. endswith()

print(b['Name'])
print(b['Name'].str.endswith('e'))

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object
0     True
1    False
2     True
3    False
4     True
Name: Name, dtype: bool

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [ ]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.