<a href="https://colab.research.google.com/github/suyogy1-bot/Numpy/blob/main/Pandas_Class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 1: Introduction & Setup
Welcome to your first class on **Pandas**. In this session, we'll learn what Pandas is, why we use it, and how to get started with Series and DataFrames.

## 1 What is Pandas and Why Use It?
Pandas is a powerful **Python library** for data analysis and manipulation.

Key points:
- Provides two main data structures: **Series** (1D) and **DataFrame** (2D).
- Makes working with tabular data easy and fast.
- Ideal for cleaning, transforming, and analyzing datasets.
- Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

## 2 Installing & Importing Pandas
To install pandas, open your terminal or command prompt and run:
```bash
pip install pandas
```
Then, you can import it in Python as follows:

In [1]:
import pandas as pd

## 3 Understanding Series & DataFrame
- **Series**: One-dimensional labeled array, like a column in Excel.
- **DataFrame**: Two-dimensional table, similar to an Excel sheet or SQL table.

### Creating a Series from Python Lists or Dictionaries

In [2]:
marks = pd.Series([30,40,50,60,70])
marks

0    30
1    40
2    50
3    60
4    70
dtype: int64

In [3]:
marks[2]

np.int64(50)

In [4]:
marks = pd.Series([30,40,50,60,70], index=['a','b','c','d','e'])
marks

a    30
b    40
c    50
d    60
e    70
dtype: int64

### Creating a DataFrame

In [6]:
info = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'city': ['New York', 'San Francisco', 'Los Angeles']
})
info

      name  age           city
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [7]:
info['age']

0    25
1    30
2    35
Name: age, dtype: int64

In [9]:
# To get specific row we use .loc

info.iloc[1]

name              Bob
age                30
city    San Francisco
Name: 1, dtype: object

In [10]:
# To get specific value
info.loc[1,'name']

'Bob'

### Creating DataFrame from NumPy Arrays

In [12]:
import numpy as np
data = np.eye(3)
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
info = pd.DataFrame(data, columns = ['Name','age','marks'])
info

   Name  age  marks
0   1.0  0.0    0.0
1   0.0  1.0    0.0
2   0.0  0.0    1.0

In [15]:
info.loc[2]

Name     0.0
age      0.0
marks    1.0
Name: 2, dtype: float64

In [ ]:
#Generate a 3x4 matrix with random numbers 1-13
# using numpy
# name the columns as [A,B,C,D]

In [18]:
arr = np.random.randint(1,13, size=(3,4))
arr
info = pd.DataFrame(arr, columns=['A','B','C','D'])
info

   A  B  C  D
0  3  1  3  8
1  3  7  8  7
2  7  5  3  5

### Reading CSV / Excel Files (Sneak Peek)
You can read external data using:
```python
pd.read_csv('file.csv')
```
```python
pd.read_excel('file.xlsx')
```
We will explore this in detail later.

---
**Summary**
- Pandas is a must-know library for data analysis.
- We learned about Series & DataFrames.
- We saw how to create them from lists, dictionaries, NumPy arrays, and got a sneak peek at CSV/Excel files.