<a href="https://colab.research.google.com/github/suyogy1-bot/Numpy_Pandas/blob/main/Class_notes/Pandas_class8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 8: Working with Time Series
Welcome to **Class 8** of our Pandas series. Today we’ll learn how to handle and analyze time series data.

## 1. Converting Columns to Datetime (`pd.to_datetime`)
- Use `pd.to_datetime()` to convert strings or numbers into datetime objects.
- Once converted, Pandas recognizes them as dates, enabling powerful operations.

In [14]:
import pandas as pd

# 1. Create the dataset
data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005],
    "OrderDate": ["2024-01-05", "2024/01/12", "15-01-2024", "2024-01-20", "20240125"],
    "Customer": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Amount": [250, 400, 150, 300, 500]
}

In [15]:
df = pd.DataFrame(data)
df

   OrderID   OrderDate Customer  Amount
0     1001  2024-01-05    Alice     250
1     1002  2024/01/12      Bob     400
2     1003  15-01-2024  Charlie     150
3     1004  2024-01-20    David     300
4     1005    20240125     Emma     500

In [3]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'], errors = "coerce")
df

   OrderID  OrderDate Customer  Amount
0     1001 2024-01-05    Alice     250
1     1002        NaT      Bob     400
2     1003        NaT  Charlie     150
3     1004 2024-01-20    David     300
4     1005        NaT     Emma     500

In [5]:
df['OrderDate'].dtype

dtype('<M8[ns]')

In [17]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'], format = 'mixed', errors = 'coerce')
df

   OrderID  OrderDate Customer  Amount
0     1001 2024-01-05    Alice     250
1     1002 2024-01-12      Bob     400
2     1003 2024-01-15  Charlie     150
3     1004 2024-01-20    David     300
4     1005 2024-01-25     Emma     500

In [12]:
pd.to_datetime(df['OrderDate'], errors = 'coerce', format = 'mixed').dt.strftime('%d-%m-%Y')

0    05-01-2024
1    12-01-2024
2    15-01-2024
3    20-01-2024
4    25-01-2024
Name: OrderDate, dtype: object

## 2. Setting DateTime Index & Resampling
- Set a datetime column as the index with `set_index()`.
- Resample time series using `resample('ME').mean()` or other rules ('D', 'W', 'YE').
- Useful for aggregating data by time periods.

In [18]:
#Step 1 :- OrderDate set as Index

df_idex = df.set_index('OrderDate')
df_idex

            OrderID Customer  Amount
OrderDate
2024-01-05     1001    Alice     250
2024-01-12     1002      Bob     400
2024-01-15     1003  Charlie     150
2024-01-20     1004    David     300
2024-01-25     1005     Emma     500

In [22]:
# Step 2 :- We will resample complete data
# according to month and we will get the total
# amount of that month

monthly_amount = df_idex.resample('ME')['Amount'].sum()
monthly_amount

OrderDate
2024-01-31    1600
Freq: ME, Name: Amount, dtype: int64

In [20]:
daily_amount = df_idex.resample('D')['Amount'].sum()
daily_amount

OrderDate
2024-01-05    250
2024-01-06      0
2024-01-07      0
2024-01-08      0
2024-01-09      0
2024-01-10      0
2024-01-11      0
2024-01-12    400
2024-01-13      0
2024-01-14      0
2024-01-15    150
2024-01-16      0
2024-01-17      0
2024-01-18      0
2024-01-19      0
2024-01-20    300
2024-01-21      0
2024-01-22      0
2024-01-23      0
2024-01-24      0
2024-01-25    500
Freq: D, Name: Amount, dtype: int64

In [23]:
yearly_avg = df_idex.resample('YE')['Amount'].mean()
yearly_avg

OrderDate
2024-12-31    320.0
Freq: YE-DEC, Name: Amount, dtype: float64

In [25]:
weekly_avg = df_idex.resample('W')['Amount'].mean()
weekly_avg

OrderDate
2024-01-07    250.0
2024-01-14    400.0
2024-01-21    225.0
2024-01-28    500.0
Freq: W-SUN, Name: Amount, dtype: float64

## mini-project

Converting columns to datetime (pd.to_datetime)

Setting a DateTime index & resampling

In [30]:

# 1️⃣ Create a dataset of website visits (string dates + visit counts)

df = pd.DataFrame({
    'VisitDate': ['2023-01-01', '2023-01-02',
                  '2023-01-03', '2023-01-04', '2023-01-05'],

    'VisitCounts': [100, 200,
                    300, 400, 500]
})

print(f"This is the original dataframe:\n {df.dtypes}")

# 2️⃣ Convert VisitDate to datetime

df['VisitDate'] = pd.to_datetime(df['VisitDate'], format = 'mixed', errors = 'coerce')

print(f"Converted VisitDate into Datetime:\n {df}")
print(df.dtypes)

# 3️⃣ Set VisitDate as the index

df = df.set_index('VisitDate')
print(f"Set VisitDate as the index:\n {df}")

# 4️⃣ Resample to get total visitors per month

monthly_visitors = df.resample('ME')['VisitCounts'].sum()
print(f"Total visitors per month:\n {monthly_visitors}")

# 5️⃣ Resample to get average visitors per week

weekly_avg_visitors = df.resample('W')['VisitCounts'].mean()
print(f"Average visitors per week:\n {weekly_avg_visitors}")

This is the original dataframe:
 VisitDate      object
VisitCounts     int64
dtype: object
Converted VisitDate into Datetime:
    VisitDate  VisitCounts
0 2023-01-01          100
1 2023-01-02          200
2 2023-01-03          300
3 2023-01-04          400
4 2023-01-05          500
VisitDate      datetime64[ns]
VisitCounts             int64
dtype: object
Set VisitDate as the index:
             VisitCounts
VisitDate
2023-01-01          100
2023-01-02          200
2023-01-03          300
2023-01-04          400
2023-01-05          500
Total visitors per month:
 VisitDate
2023-01-31    1500
Freq: ME, Name: VisitCounts, dtype: int64
Average visitors per week:
 VisitDate
2023-01-01    100.0
2023-01-08    350.0
Freq: W-SUN, Name: VisitCounts, dtype: float64

---
## Summary
- Converted columns to datetime with `pd.to_datetime`.
- Set DateTime index and resampled data.
- Performed date-based filtering and slicing.
- Applied rolling and expanding window calculations.