<a href="https://colab.research.google.com/github/suyogy1-bot/Numpy_Pandas/blob/main/Class_notes/pandas_class7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [ ]:
import pandas as pd
# Dataset 1: Product details
df1 = pd.DataFrame({
    'ProductID': [101,102,103],
    'ProductName': ['Pen', 'Notebook', 'Marker'],
    'Price': [10, 50, 30]})


# Dataset 2: More products (same columns as df1 → good for vertical stacking)

df2 = pd.DataFrame({
    'ProductID': [104,105,106],
    'ProductName': ['Pencil', 'Eraser', 'Ruler'],
    'Price': [5, 20, 15]})

# Dataset 3: Additional info (different columns → good for horizontal stacking)

df3 = pd.DataFrame({
    'Stock': [100, 50, 75],
    'Rating': [4.5, 4.7, 4.8]
})

print(f"DF1 {df1}")
print(f"DF2 {df2}")
print(f"DF3 {df3}")

DF1    ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
DF2    ProductID ProductName  Price
0        104      Pencil      5
1        105      Eraser     20
2        106       Ruler     15
DF3    Stock  Rating
0    100     4.5
1     50     4.7
2     75     4.8

In [ ]:
#1. Vertical stacking (axis = 0)

# By default concat does vertical stacking

vertical_stacking = pd.concat([df1, df2])
print(f"Vertical Stacking:\n{vertical_stacking}")

Vertical Stacking:
   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
0        104      Pencil      5
1        105      Eraser     20
2        106       Ruler     15

In [ ]:
# To change index values

vertical_stacking = pd.concat([df1, df2], axis=0, ignore_index=True)
print(f"Vertical Stacking:\n{vertical_stacking}")

Vertical Stacking:
   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser     20
5        106       Ruler     15

In [ ]:
#2. Horizontal Stacking (axis = 1)

horizontal_stacking = pd.concat([df1, df3], axis=1)
print(f"Horizontal Stacking:\n{horizontal_stacking}")

Horizontal Stacking:
   ProductID ProductName  Price  Stock  Rating
0        101         Pen     10    100     4.5
1        102    Notebook     50     50     4.7
2        103      Marker     30     75     4.8

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [ ]:
# We have to concat df1 and df2 rows wise

Product = pd.concat([df1, df2], ignore_index=True)
print(f"Produce Df:\n{Product}")

Sales = pd.DataFrame({
    'ProductID': [101, 103, 105],
    'Sales': [1000, 800, 1200]
})

print(f"Sales Df:\n{Sales}")

Revenue = pd.DataFrame({
    'ProductID': [101, 102, 103],
    'Revenue': [2000, 1500, 2500]})

print(f"Revenue Df:\n{Revenue}")

Produce Df:
   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser     20
5        106       Ruler     15
Sales Df:
   ProductID  Sales
0        101   1000
1        103    800
2        105   1200
Revenue Df:
   ProductID  Revenue
0        101     2000
1        102     1500
2        103     2500

In [ ]:
#1. Inner Join (Done Dataframes ke beech only matching ProductId)

pd.merge(Product,Sales, how='inner')

   ProductID ProductName  Price  Sales
0        101         Pen     10   1000
1        103      Marker     30    800
2        105      Eraser     20   1200

In [ ]:
#2. Left Join (Take left full table and only common element of Right Table)

pd.merge(Product,Sales, how='left')

   ProductID ProductName  Price   Sales
0        101         Pen     10  1000.0
1        102    Notebook     50     NaN
2        103      Marker     30   800.0
3        104      Pencil      5     NaN
4        105      Eraser     20  1200.0
5        106       Ruler     15     NaN

In [ ]:
#3. Right Join (Take Right Table full and Left Table only common elements)

pd.merge(Product, Sales, how='right')

   ProductID ProductName  Price  Sales
0        101         Pen     10   1000
1        103      Marker     30    800
2        105      Eraser     20   1200

In [ ]:
#4. Outer join (Everthing, even unmatched)

outer = pd.merge(Product, Sales, how='outer')
print(f"Outer Join:\n{outer}")

Outer Join:
   ProductID ProductName  Price   Sales
0        101         Pen     10  1000.0
1        102    Notebook     50     NaN
2        103      Marker     30   800.0
3        104      Pencil      5     NaN
4        105      Eraser     20  1200.0
5        106       Ruler     15     NaN

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [ ]:
#1. Join stock information to product

Sales = pd.DataFrame({
    'UnitsSold': [101, 103, 105, 200, 300]},
    index = [101, 102, 103, 104, 105]
)

print(f"Sales:\n{Sales}")

Sales:
     UnitsSold
101        101
102        103
103        105
104        200
105        300

In [ ]:
p_indexed = Product.set_index('ProductID')
joined = p_indexed.join(Sales)
print(f"Joined:\n{joined}")

Joined:
          ProductName  Price  UnitsSold
ProductID
101               Pen     10      101.0
102          Notebook     50      103.0
103            Marker     30      105.0
104            Pencil      5      200.0
105            Eraser     20      300.0
106             Ruler     15        NaN

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

In [5]:
import pandas as pd

# Re-defining df1 and df2 as they are needed for Product DataFrame
df1 = pd.DataFrame({
    'ProductID': [101,102,103],
    'ProductName': ['Pen', 'Notebook', 'Marker'],
    'Price': [10, 50, 30]})

df2 = pd.DataFrame({
    'ProductID': [104,105,106],
    'ProductName': ['Pencil', 'Eraser', 'Ruler'],
    'Price': [5, 20, 15]})

# Re-defining Product, Sales, and Revenue DataFrames with 'ProductID'
Product = pd.concat([df1, df2], ignore_index=True)

Sales = pd.DataFrame({
    'ProductID': [101, 103, 105],
    'Sales': [1000, 800, 1200]
})

Revenue = pd.DataFrame({
    'ProductID': [101, 102, 103],
    'Revenue': [2000, 1500, 2500]})


print('--- 1. Combining Sales and Revenue Data ---')

# Merge Product with Sales data
product_sales = pd.merge(Product, Sales, on='ProductID', how='left')
print(f"Product and Sales Merged (Left Join):\n{product_sales}\n")

# Merge the combined data with Revenue data
combined_performance = pd.merge(product_sales, Revenue, on='ProductID', how='left')
print(f"Combined Performance (Product, Sales, Revenue - Left Join):\n{combined_performance}\n")

# Handle missing values (e.g., fill NaN with 0 for Sales and Revenue)
combined_performance_filled = combined_performance.fillna(0)
print(f"Combined Performance (NaN filled with 0):\n{combined_performance_filled}\n")

print('\n--- 2. Merging Students with Marks ---')

# Create sample Student DataFrame
students_df = pd.DataFrame({
    'StudentID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David']
})

# Create sample Marks DataFrame
marks_df = pd.DataFrame({
    'StudentID': [1, 2, 3, 5],
    'Subject': ['Math', 'Science', 'History', 'Math'],
    'Marks': [85, 92, 78, 65]
})

print(f"Students DataFrame:\n{students_df}\n")
print(f"Marks DataFrame:\n{marks_df}\n")

# Merge students with their marks (inner join to get only students with marks)
student_marks_inner = pd.merge(students_df, marks_df, on='StudentID', how='inner')
print(f"Student Marks (Inner Join):\n{student_marks_inner}\n")

# Merge students with their marks (left join to keep all students)
student_marks_left = pd.merge(students_df, marks_df, on='StudentID', how='left')
print(f"Student Marks (Left Join):\n{student_marks_left}\n")

# Analyze missing data in the left join
print("Missing data after left join:\n", student_marks_left.isnull().sum())

--- 1. Combining Sales and Revenue Data ---
Product and Sales Merged (Left Join):
   ProductID ProductName  Price   Sales
0        101         Pen     10  1000.0
1        102    Notebook     50     NaN
2        103      Marker     30   800.0
3        104      Pencil      5     NaN
4        105      Eraser     20  1200.0
5        106       Ruler     15     NaN

Combined Performance (Product, Sales, Revenue - Left Join):
   ProductID ProductName  Price   Sales  Revenue
0        101         Pen     10  1000.0   2000.0
1        102    Notebook     50     NaN   1500.0
2        103      Marker     30   800.0   2500.0
3        104      Pencil      5     NaN      NaN
4        105      Eraser     20  1200.0      NaN
5        106       Ruler     15     NaN      NaN

Combined Performance (NaN filled with 0):
   ProductID ProductName  Price   Sales  Revenue
0        101         Pen     10  1000.0   2000.0
1        102    Notebook     50     0.0   1500.0
2        103      Marker     30   800.0   2500.0
3        104      Pencil      5     0.0      0.0
4        105      Eraser     20  1200.0      0.0
5        106       Ruler     15     0.0      0.0


--- 2. Merging Students with Marks ---
Students DataFrame:
   StudentID     Name
0          1    Alice
1          2      Bob
2          3  Charlie
3          4    David

Marks DataFrame:
   StudentID  Subject  Marks
0          1     Math     85
1          2  Science     92
2          3  History     78
3          5     Math     65

Student Marks (Inner Join):
   StudentID     Name  Subject  Marks
0          1    Alice     Math     85
1          2      Bob  Science     92
2          3  Charlie  History     78

Student Marks (Left Join):
   StudentID     Name  Subject  Marks
0          1    Alice     Math   85.0
1          2      Bob  Science   92.0
2          3  Charlie  History   78.0
3          4    David      NaN    NaN

Missing data after left join:
 StudentID    0
Name         0
Subject      1
Marks        1
dtype: int64

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [3]:

# 1. Create three DataFrames: Products, Sales, and Revenue

import pandas as pd

Products = pd.DataFrame({
    'SKU': [101,102,103],
    'ProductName': ['Pen', 'Notebook', 'Marker'],
    'Price': [10, 50, 30]})


Sales = pd.DataFrame({
    'SKU': [101, 103, 105],
    'UnitsSold': [1000, 800, 1200]
})

Revenue = pd.DataFrame({
    'SKU': [101, 102, 103],
    'Revenue': [2000, 1500, 2500]})

print(f"Products:\n{Products}")
print(f"Sales:\n{Sales}")
print(f"Revenue:\n{Revenue}")


# 2. Concatenate them vertically and horizontally

concat_vertical = pd.concat([Products, Sales], axis=0, ignore_index=True)
print(f"Vertical Concat:\n{concat_vertical}")

concat_horizontal = pd.concat([Products, Revenue], axis=1)
print(f"Horizontal Concat:\n{concat_horizontal}")

# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)

pd.merge(Sales, Revenue, how='inner')
pd.merge(Sales, Revenue, how='left')
pd.merge(Sales, Revenue, how='right')
pd.merge(Sales, Revenue, how='outer')

# 4. Join Products with Sales based on index or a key

p_indexed = Products.set_index('SKU')
joined = p_indexed.join(Sales)
print(f"Joined:\n{joined}")

# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps

print(joined.isna())
print(joined.info())
print(joined.describe())

Products:
   SKU ProductName  Price
0  101         Pen     10
1  102    Notebook     50
2  103      Marker     30
Sales:
   SKU  UnitsSold
0  101       1000
1  103        800
2  105       1200
Revenue:
   SKU  Revenue
0  101     2000
1  102     1500
2  103     2500
Vertical Concat:
   SKU ProductName  Price  UnitsSold
0  101         Pen   10.0        NaN
1  102    Notebook   50.0        NaN
2  103      Marker   30.0        NaN
3  101         NaN    NaN     1000.0
4  103         NaN    NaN      800.0
5  105         NaN    NaN     1200.0
Horizontal Concat:
   SKU ProductName  Price  SKU  Revenue
0  101         Pen     10  101     2000
1  102    Notebook     50  102     1500
2  103      Marker     30  103     2500
Joined:
    ProductName  Price  SKU  UnitsSold
SKU
101         Pen     10  NaN        NaN
102    Notebook     50  NaN        NaN
103      Marker     30  NaN        NaN
     ProductName  Price   SKU  UnitsSold
SKU
101        False  False  True       True
102        False  False  True       True
103        False  False  True       True
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 101 to 103
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductName  3 non-null      object
 1   Price        3 non-null      int64
 2   SKU          0 non-null      float64
 3   UnitsSold    0 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 120.0+ bytes
None
       Price  SKU  UnitsSold
count    3.0  0.0        0.0
mean    30.0  NaN        NaN
std     20.0  NaN        NaN
min     10.0  NaN        NaN
25%     20.0  NaN        NaN
50%     30.0  NaN        NaN
75%     40.0  NaN        NaN
max     50.0  NaN        NaN

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.