<a href="https://colab.research.google.com/github/suyogy1-bot/Numpy_Pandas/blob/main/Pandas_Class5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 5: Sorting & Basic Statistics
Welcome to **Class 5** of our Pandas series. Today we’ll learn how to sort data and calculate basic statistics.

## 1. Sorting Data
- Use `sort_values(by='col')` to sort by column values.
- Use `ascending=False` for descending order.
- Sort by multiple columns by passing a list.
- `sort_index()` sorts by row or column index.

In [32]:
import pandas as pd

data = pd.DataFrame({
    "Product": ['Pen', 'Notebook', 'Pencil', 'Marker', 'Eraser', 'Sharpener'],
    'Price': [10, 50, 5, 30, 8 ,12],
    'Stock': [100, 60, 200, 80, 150, 120],
    'Rating': [4.5, 4.7, 4.2, 4.8, 4.3, 4.4]
})

df = data
df

     Product  Price  Stock  Rating
0        Pen     10    100     4.5
1   Notebook     50     60     4.7
2     Pencil      5    200     4.2
3     Marker     30     80     4.8
4     Eraser      8    150     4.3
5  Sharpener     12    120     4.4

In [ ]:
#1. sort by a single column -> Price (ascending)

df_sorted = df.sort_values(by='Price')
df_sorted

     Product  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1   Notebook     50     60     4.7

In [ ]:
df_sorted_desc = df.sort_values(by='Price', ascending=False)
df_sorted_desc

     Product  Price  Stock  Rating
1   Notebook     50     60     4.7
3     Marker     30     80     4.8
5  Sharpener     12    120     4.4
0        Pen     10    100     4.5
4     Eraser      8    150     4.3
2     Pencil      5    200     4.2

In [ ]:
#2. Sort by a single column -> Rating (descending)

df_sorted_rating = df.sort_values(by='Rating', ascending=False)
df_sorted_rating

     Product  Price  Stock  Rating
3     Marker     30     80     4.8
1   Notebook     50     60     4.7
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
4     Eraser      8    150     4.3
2     Pencil      5    200     4.2

In [ ]:
#3. Sorting multiple columns -> Price and Stock

df_sorted_price_stock = df.sort_values(by=['Price', 'Stock'])
df_sorted_price_stock

     Product  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1   Notebook     50     60     4.7

In [ ]:
# sorting all the columns

df_sorted_all_columns = df.sort_values(by=['Price', 'Stock', 'Rating'], ascending=[True, False, False])
df_sorted_all_columns

     Product  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1   Notebook     50     60     4.7

In [ ]:
#4. sort_index() -> in descending order.

df_sorted_index = df.sort_index(ascending=False)
df_sorted_index

     Product  Price  Stock  Rating
5  Sharpener     12    120     4.4
4     Eraser      8    150     4.3
3     Marker     30     80     4.8
2     Pencil      5    200     4.2
1   Notebook     50     60     4.7
0        Pen     10    100     4.5

## 2. Descriptive Statistics
- `mean()`, `median()`, `mode()` for central tendency.
- `std()` for standard deviation.
- `describe()` for a summary of stats (count, mean, std, min, quartiles, max).

In [14]:
import numpy as np

#1. Mean of numeric columns only

df.mean(numeric_only = True)
# mean_price = df['Price'].mean()
# mean_stock = df['Stock'].mean()
# mean_rating = df['Rating'].mean()

Price      19.166667
Stock     118.333333
Rating      4.483333
dtype: float64

In [15]:
#2. Median of numeric columns only

df.median(numeric_only= True)

Price      11.00
Stock     110.00
Rating      4.45
dtype: float64

In [18]:
#3. Mode

df.mode()

     Product  Price  Stock  Rating
0     Eraser      5     60     4.2
1     Marker      8     80     4.3
2   Notebook     10    100     4.4
3        Pen     12    120     4.5
4     Pencil     30    150     4.7
5  Sharpener     50    200     4.8

In [19]:
#4. standard deviation

df.std(numeric_only= True)

Price     17.486185
Stock     50.760877
Rating     0.231661
dtype: float64

In [20]:
#5. Complete statistical values of columns

df.describe()

           Price       Stock    Rating
count   6.000000    6.000000  6.000000
mean   19.166667  118.333333  4.483333
std    17.486185   50.760877  0.231661
min     5.000000   60.000000  4.200000
25%     8.500000   85.000000  4.325000
50%    11.000000  110.000000  4.450000
75%    25.500000  142.500000  4.650000
max    50.000000  200.000000  4.800000

## 3. Counting Values
- `value_counts()` shows the frequency of unique values in a Series.
- Use `normalize=True` to see percentages instead of counts.

In [21]:
df

     Product  Price  Stock  Rating
0        Pen     10    100     4.5
1   Notebook     50     60     4.7
2     Pencil      5    200     4.2
3     Marker     30     80     4.8
4     Eraser      8    150     4.3
5  Sharpener     12    120     4.4

In [25]:
#1. count how many times each product appears

print(df['Product'].value_counts)

<bound method IndexOpsMixin.value_counts of 0          Pen
1     Notebook
2       Pencil
3       Marker
4       Eraser
5    Sharpener
Name: Product, dtype: object>

In [26]:
#2. Show percentage instead of counts.

print(df['Product'].value_counts(normalize= True))

Product
Pen          0.166667
Notebook     0.166667
Pencil       0.166667
Marker       0.166667
Eraser       0.166667
Sharpener    0.166667
Name: proportion, dtype: float64

In [27]:
#3. Count values of column Rating.

print(df['Rating'].value_counts())

Rating
4.5    1
4.7    1
4.2    1
4.8    1
4.3    1
4.4    1
Name: count, dtype: int64

## 4. Correlation & Covariance
- `corr()` computes correlation between numeric columns.
- `cov()` computes covariance.
- Correlation values range from -1 (negative) to +1 (positive).

In [35]:
#1. Correlation between all numeric columns

# +ve correlation -> one increase and other increases
# -ve correlation -> one decrease and other increases and vice-versa

df.corr(numeric_only= True)

           Price     Stock    Rating
Price   1.000000 -0.804028  0.820402
Stock  -0.804028  1.000000 -0.921257
Rating  0.820402 -0.921257  1.000000

Covariance is a statistical measure that tells you how two numerical variables vary with respect to each other. Think of having two columns of numbers, X and Y (for example: hours studied and exam score). Covariance looks at each pair of values and checks:

- When X is above its mean, is Y also usually above its mean?

- When X is below its mean, is Y also usually below its mean?

If yes, the covariance is positive, meaning the variables tend to move together.

If when X is above its mean, Y is usually below its mean (and vice versa), the covariance is negative, meaning the variables tend to move in opposite directions.

In [34]:
#2. Covariance between all numeric columns

df.cov(numeric_only= True)

             Price        Stock     Rating
Price   305.766667  -713.666667   3.323333
Stock  -713.666667  2576.666667 -10.833333
Rating    3.323333   -10.833333   0.053667

In [36]:
#3. Correlation between 2 columns Price and Stock

df['Price'].corr(df['Stock'])

np.float64(-0.8040280933316356)

## Mini Practice
1. Build a DataFrame with columns: Name, Age, Score, Height.
2. Sort the data by Score (descending).
3. Get mean, median, mode, and std of numeric columns.
4. Use value_counts on Name or any categorical column.
5. Compute corr() and cov() for all numeric columns.

In [30]:
# Write your mini practice solution here

# 1. Build a DataFrame with columns: Name, Age, Score, Height

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'Score': [85, 90, 75, 88, 92],
    'Height': [165, 170, 160, 175, 180]
})

# 2. Sort the data by Score (descending)

df_sorted = df.sort_values(by='Score', ascending=False)
print(df_sorted)

# 3. Get mean, median, mode, and std of numeric columns

print(df.describe())

# 4. Use value_counts on Name or any categorical column

print(df['Name'].value_counts())

# 5. Compute corr() and cov() for all numeric columns

print(df.corr(numeric_only= True))
print(df.cov(numeric_only=True))

      Name  Age  Score  Height
4      Eve   45     92     180
1      Bob   30     90     170
3    David   40     88     175
0    Alice   25     85     165
2  Charlie   35     75     160
             Age      Score      Height
count   5.000000   5.000000    5.000000
mean   35.000000  86.000000  170.000000
std     7.905694   6.670832    7.905694
min    25.000000  75.000000  160.000000
25%    30.000000  85.000000  165.000000
50%    35.000000  88.000000  170.000000
75%    40.000000  90.000000  175.000000
max    45.000000  92.000000  180.000000
Name
Alice      1
Bob        1
Charlie    1
David      1
Eve        1
Name: count, dtype: int64
             Age     Score    Height
Age     1.000000  0.284427  0.700000
Score   0.284427  1.000000  0.876984
Height  0.700000  0.876984  1.000000
          Age  Score  Height
Age     62.50  15.00   43.75
Score   15.00  44.50   46.25
Height  43.75  46.25   62.50

---
## Summary
- Learned to sort by columns with `sort_values` and by index with `sort_index`.
- Explored descriptive statistics: mean, median, mode, std, describe.
- Counted values with `value_counts`.
- Calculated correlation and covariance.