<a href="https://colab.research.google.com/github/suyogy1-bot/Numpy_Pandas/blob/main/Pandas_class6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [1]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [4]:
# What is the average salary of each department

avg_salary = df.groupby('Department')['Salary'].mean()

In [7]:
# How many employees are there in each department

count_employee = df.groupby('Department')['Employee'].count()
count_employee

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

In [8]:
multi_stats = df.groupby('Department').agg({'Salary': ['mean', 'min', 'max'], 'Employee': 'count'})
multi_stats

                  Salary               Employee
                    mean    min    max    count
Department
Finance     61000.000000  58000  65000        3
HR          51000.000000  50000  52000        2
IT          72333.333333  70000  75000        3

In [10]:
avg_age = df.groupby('Department')['Age'].mean()
avg_age

Department
Finance    29.333333
HR         28.500000
IT         31.000000
Name: Age, dtype: float64

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [14]:
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [15]:
avg_salary_and_age = df.groupby('Department').agg({'Salary': 'mean', 'Age': 'max'})
avg_salary_and_age

                  Salary  Age
Department
Finance     61000.000000   35
HR          51000.000000   29
IT          72333.333333   32

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [24]:
df.pivot_table(index='Department', values='Salary', aggfunc='mean')

                  Salary
Department
Finance     61000.000000
HR          51000.000000
IT          72333.333333

In [25]:
df.pivot_table(index='Department', values=['Salary','Age'], aggfunc='mean')

                  Age        Salary
Department
Finance     29.333333  61000.000000
HR          28.500000  51000.000000
IT          31.000000  72333.333333

In [28]:
# Age range -> 25-30, 30-35

df['Age_group'] = pd.cut(df['Age'], bins=[25, 30, 35], labels = ['25-30', '30-35'])
df

  Department Employee  Salary  Age           City Age_group
0         HR     John   50000   28       New York     25-30
1         IT    Sarah   70000   32  San Francisco     30-35
2         IT     Mike   72000   30  San Francisco     25-30
3    Finance     Anna   65000   27    Los Angeles     25-30
4    Finance      Tom   60000   35    Los Angeles     30-35
5         HR    Laura   52000   29       New York     25-30
6         IT    Steve   75000   31  San Francisco     30-35
7    Finance     Kate   58000   26    Los Angeles     25-30

In [30]:
# This works as simple just like .count()

pd.crosstab(df['Department'], df['Age_group'])

Age_group   25-30  30-35
Department
Finance         2      1
HR              2      0
IT              1      2

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [32]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City

df = pd.DataFrame({
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26],
    "City": ["New York", "San Francisco", "San Francisco", "Los Angeles", "Los Angeles", "New York", "San Francisco", "Los Angeles"]
})

# 2. Group by Department to get average Salary and max Age

avg_salary = df.groupby('Department')['Salary'].mean()
max_age = df.groupby('Department')['Age'].max()
print("Average Salary by Department:")
print(avg_salary)
print("\nMaximum Age by Department:")
print(max_age)

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department

multi_stats = df.groupby('Department').agg({'Salary': ['mean', 'min', 'max'], 'Employee': 'count'})
print("\nMultiple Aggregations:")
print(multi_stats)

# 4. Create a pivot_table to see mean Salary by Department and City

pivot_table = pd.pivot_table(df, values='Salary', index='Department', columns='City', aggfunc='mean')
print("\nPivot Table:")
print(pivot_table)

# 5. Build a crosstab for Department vs City

crosstab = pd.crosstab(df['Department'], df['City'])
print("\nCrosstab:")
print(crosstab)

Average Salary by Department:
Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

Maximum Age by Department:
Department
Finance    35
HR         29
IT         32
Name: Age, dtype: int64

Multiple Aggregations:
                  Salary               Employee
                    mean    min    max    count
Department
Finance     61000.000000  58000  65000        3
HR          51000.000000  50000  52000        2
IT          72333.333333  70000  75000        3

Pivot Table:
City        Los Angeles  New York  San Francisco
Department
Finance         61000.0       NaN            NaN
HR                  NaN   51000.0            NaN
IT                  NaN       NaN   72333.333333

Crosstab:
City        Los Angeles  New York  San Francisco
Department
Finance               3         0              0
HR                    0         2              0
IT                    0         0              3

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.