# NumPy Matrix + Pandas Assignment

## Q1. Create a 3×3 NumPy Matrix

### Input
```
1 2 3
4 5 6
7 8 9
```

### Output
```python
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

In [4]:
import numpy as np
import pandas as pd

arr = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
arr

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Q2. Multiply Matrix by 2

### Input
```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

### Output
```python
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
```

In [6]:
arr1 = arr * 2
arr1

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

## Q3. Find Row-wise Sum

### Output
```python
[ 6 15 24]
```

In [16]:
arr.sum(axis=1)

matrix([[ 6],
        [15],
        [24]])

## Q4. Find Column-wise Sum

### Output
```python
[12 15 18]
```

In [18]:
arr.sum(axis=0)

matrix([[12, 15, 18]])

## Q5. Extract Second Row

### Output
```python
[4 5 6]
```

In [20]:
arr[1]

matrix([[4, 5, 6]])

## Q6. Create DataFrame

| Name | Marks |
|------|------|
| Raj | 80 |
| Amit | 70 |
| Neha | 90 |
| Priya | 85 |

In [33]:
df = pd.DataFrame({
    "Name": ["Raj", "Amit", "Neha", "Priya"],
    "Marks": [80, 70, 90, 85]
})

df

    Name  Marks
0    Raj     80
1   Amit     70
2   Neha     90
3  Priya     85

## Q7. Add Bonus Column

Bonus = Marks + 5

### Expected Output
```
Raj    80   85
Amit   70   75
Neha   90   95
Priya  85   90
```

In [27]:
df['Bonus'] = df['Marks'] + 5
df

    Name  Marks  Bonus
0    Raj     80     85
1   Amit     70     75
2   Neha     90     95
3  Priya     85     90

## Q8. Display Students Having Marks > 80

### Expected Output
```
Neha   90
Priya  85
```

In [35]:
df[df['Marks'] > 80]

    Name  Marks
2   Neha     90
3  Priya     85

## Q9. Print First Row Using iloc

### Expected Output
```
Raj 80
```

In [37]:
df.iloc[0]

Name     Raj
Marks     80
Name: 0, dtype: object

## Q10. Print Third Row Using iloc

### Expected Output
```
Neha 90
```

In [39]:
df.iloc[2]

Name     Neha
Marks      90
Name: 2, dtype: object

## Q11. Print First 2 Rows Using iloc

### Expected Output
```
Raj 80
Amit 70
```

In [41]:
df.iloc[:2]

   Name  Marks
0   Raj     80
1  Amit     70

## Q12. Print Only Name Column Using iloc

### Expected Output
```
Raj
Amit
Neha
Priya
```

In [45]:
df.iloc[:, 0]

0      Raj
1     Amit
2     Neha
3    Priya
Name: Name, dtype: object

## Q13. Update Amit's Marks to 75

### Expected Output
```
Amit 75
```

In [47]:
df.loc[df['Name'] == 'Amit', 'Marks'] = 75
df

    Name  Marks
0    Raj     80
1   Amit     75
2   Neha     90
3  Priya     85

## Q14. Sort DataFrame by Marks (Descending)

### Expected Output
```
Neha  90
Priya 85
Raj   80
Amit  75
```

In [49]:
df.sort_values('Marks', ascending=False)

    Name  Marks
2   Neha     90
3  Priya     85
0    Raj     80
1   Amit     75