
# Pandas Assignment — Class 1

## Level: Basic

### Topics Covered
- What is Pandas
- Importing Pandas
- Series
- DataFrame
- Creating Series from List
- Creating Series from Dictionary
- Creating DataFrame from Dictionary
- Creating DataFrame from NumPy Array

### Instructions
- Use Pandas in every question.
- Write code in the blank code cell below each question.
- Print the required output.


# Q1. Import Pandas

## Problem Statement
Import the Pandas library and display its version.

## Sample Output
```python
2.x.x
```

In [7]:
import pandas as pd
print(pd.__version__)

2.2.2


# Q2. Create a Series from a List

## Problem Statement
Create a Pandas Series using the following list:

```python
[10, 20, 30, 40, 50]
```

## Sample Output
```python
0    10
1    20
2    30
3    40
4    50
dtype: int64
```

In [9]:
df = pd.DataFrame([10,20,30,40,50])
df

    0
0  10
1  20
2  30
3  40
4  50


# Q3. Create a Series of Student Names

## Problem Statement
Create a Series using the following names:

```python
["Aman", "Rahul", "Neha", "Priya"]
```

## Sample Output
```python
0     Aman
1    Rahul
2     Neha
3    Priya
dtype: object
```

In [13]:
df = pd.DataFrame(["Aman", "Rahul", "Neha", "Priya"])
df

       0
0   Aman
1  Rahul
2   Neha
3  Priya


# Q4. Create a Series from Dictionary

## Problem Statement
Create a Series from the following dictionary:

```python
{
    "Maths": 80,
    "Science": 75,
    "English": 90
}
```

## Sample Output
```python
Maths      80
Science    75
English    90
dtype: int64
```

In [21]:
marks = {
    "Maths": 80,
    "Science": 75,
    "English": 90
}

df = pd.DataFrame(marks, index=[0])
df

   Maths  Science  English
0     80       75       90

In [23]:
df1 = pd.Series(marks)
df1

Maths      80
Science    75
English    90
dtype: int64


# Q5. Create a Student DataFrame

## Problem Statement
Create a DataFrame with the following data:

```python
Name = ["Aman", "Rahul", "Neha"]
Age = [21, 22, 20]
```

## Sample Output
```python
    Name  Age
0   Aman   21
1  Rahul   22
2   Neha   20
```

In [25]:
Name = ["Aman", "Rahul", "Neha"]
Age = [21, 22, 20]


df = pd.DataFrame({
    "Name": Name,
    "Age": Age
})
df

    Name  Age
0   Aman   21
1  Rahul   22
2   Neha   20


# Q6. Employee DataFrame

## Problem Statement
Create a DataFrame containing:

```python
Employee = ["John", "Sara", "Mike"]
Salary = [50000, 60000, 55000]
```

## Sample Output
```python
  Employee  Salary
0     John   50000
1     Sara   60000
2     Mike   55000
```

In [27]:
Employee = ["John", "Sara", "Mike"]
Salary = [50000, 60000, 55000]

df = pd.DataFrame({
    "Employee": Employee,
    "Salary": Salary
})
df

  Employee  Salary
0     John   50000
1     Sara   60000
2     Mike   55000


# Q7. DataFrame from NumPy Array

## Problem Statement
Create the following NumPy array:

```python
[[1,2],
 [3,4],
 [5,6]]
```

Convert it into a Pandas DataFrame.

## Sample Output
```python
   0  1
0  1  2
1  3  4
2  5  6
```

In [31]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6]])
df = pd.DataFrame(arr)
df

   0  1
0  1  2
1  3  4
2  5  6


# Q8. Create a Product DataFrame

## Problem Statement
Create a DataFrame containing:

```python
Product = ["Laptop", "Mouse", "Keyboard"]
Price = [50000, 500, 1200]
```

## Sample Output
```python
    Product  Price
0    Laptop  50000
1     Mouse    500
2  Keyboard   1200
```

In [33]:
Product = ["Lapto", "Mouse", "Keyboard"]
Price = [50000, 500, 1200]

df = pd.DataFrame({
    "Product": Product,
    "Price": Price
})
df

    Product  Price
0     Lapto  50000
1     Mouse    500
2  Keyboard   1200


# Q9. Display DataFrame Information

## Problem Statement
Create a DataFrame with any 3 rows and 2 columns.

Use:

```python
df.info()
```

to display information about the DataFrame.

## Sample Output
```python
<class 'pandas.core.frame.DataFrame'>
...
```

In [39]:
arr = np.random.randint(7, size=(3,2))
arr
df = pd.DataFrame(arr)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
 1   1       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes


# Q10. Create Marks DataFrame

## Problem Statement
Create a DataFrame using:

```python
Name = ["A", "B", "C"]
Marks = [80, 75, 90]
```

Print the DataFrame.

## Sample Output
```python
  Name  Marks
0    A     80
1    B     75
2    C     90
```

In [41]:
Name = ["A","B","C"]
Marks = [80, 75, 90]

df = pd.DataFrame({
    "Name": Name,
    "Marks": Marks})
df

  Name  Marks
0    A     80
1    B     75
2    C     90