# Pandas Class 5 Assignment

## Topics
- sort_values()
- mean()
- median()
- mode()
- value_counts()
- corr()
- cov()

Difficulty: Easy to Moderate

## Q1. Sort Age in Ascending Order

Input:
Age = [25, 18, 30, 22]

Output:
18
22
25
30

In [15]:
import pandas as pd
import numpy as np

Age = [25, 18, 30, 22]

age_series = pd.Series(Age)
sorted_age = age_series.sort_values()
sorted_age

1    18
3    22
0    25
2    30
dtype: int64

## Q2. Sort Marks in Descending Order

Input:
Marks = [70, 95, 80, 60]

Output:
95
80
70
60

In [18]:
Marks = [70, 95, 80, 60]

marks = pd.Series(Marks)
sorted = marks.sort_values(ascending=False)
sorted

1    95
2    80
0    70
3    60
dtype: int64

## Q3. Find Mean Age

Input:
Age = [20, 25, 30, 25]

Output:
25.0

In [22]:
Age = [20, 25, 30, 25]

age = pd.Series(Age)
mean = age.mean()
mean

25.0

## Q4. Find Median Marks

Input:
Marks = [50, 60, 70, 80, 90]

Output:
70

In [24]:
Marks = pd.Series([50, 60, 70, 80, 90])

Marks.median()

70.0

## Q5. Find Mode

Input:
Age = [20, 25, 25, 30, 25]

Output:
25

In [26]:
Age = pd.Series([20, 25, 25, 30, 25])

Age.mode()

0    25
dtype: int64

## Q6. Find Maximum Score

Input:
Score = [78, 90, 67, 88]

Output:
90

In [28]:
Score = pd.Series([78, 90, 67, 88])
Score.max()

90

## Q7. Find Minimum Score

Input:
Score = [78, 90, 67, 88]

Output:
67

In [30]:
Score = pd.Series([78, 90, 67, 88])

Score.min()

67

## Q8. Count City Frequency

Input:
City = ['Bhopal','Indore','Bhopal','Jabalpur']

Output:
Bhopal      2
Indore      1
Jabalpur    1

In [34]:
City = pd.Series(['Bhopal','Indore','Bhopal','Jabalpur'])

City.value_counts()

Bhopal      2
Indore      1
Jabalpur    1
Name: count, dtype: int64

## Q9. Find Percentage Frequency

Input:
City = ['A','A','B','C']

Output:
A = 50%
B = 25%
C = 25%

In [40]:
City = pd.Series(['A','A',"B",'C'])

freq_percent = City.value_counts(normalize=True) * 100
freq_percent

A    50.0
B    25.0
C    25.0
Name: proportion, dtype: float64

## Q10. Sort DataFrame by Salary

Input:
Name   Salary
Aman   30000
Raj    50000
Riya   40000

Output:
Raj
Riya
Aman

In [56]:
df = pd.DataFrame({
    "Name": ['Aman', 'Raj', 'Riya'],
    "Salary": [30000, 50000, 40000]
})

a = df.sort_values(by='Salary',ascending=False)
a['Name']

1     Raj
2    Riya
0    Aman
Name: Name, dtype: object

## Q11. Find Correlation

Input:
Math = [10,20,30,40]
Science = [15,25,35,45]

Output:
1.0

In [58]:
df = pd.DataFrame({
    'Math': [10,20,30,40],
    'Science': [15,25,35,45]
})

df.corr()

         Math  Science
Math      1.0      1.0
Science   1.0      1.0

## Q12. Find Covariance

Input:
Math = [10,20,30,40]
Science = [15,25,35,45]

Output:
166.67 (approx)

In [60]:
df.cov()

               Math     Science
Math     166.666667  166.666667
Science  166.666667  166.666667

## Q13. Sort by Two Columns

Input:
Sort by City and then Age

Output:
Sorted DataFrame

In [90]:
df = pd.DataFrame({
    'City': ['dore','hopal','satna'],
    'Age': [20,5,30]
})

df

    City  Age
0   dore   20
1  hopal    5
2  satna   30

In [92]:
df.sort_values(by='City')

    City  Age
0   dore   20
1  hopal    5
2  satna   30

In [94]:
df.sort_values(by='Age')

    City  Age
1  hopal    5
0   dore   20
2  satna   30

In [100]:
df.sort_values(by=['City','Age']) 
# here it bydefault chooses the first option for sorting i.e. City

    City  Age
0   dore   20
1  hopal    5
2  satna   30

## Q14. Student Statistics

Input:
Marks = [60,70,80,90]

Output:
Mean = 75
Median = 75
Max = 90
Min = 60

In [104]:
Marks = pd.Series([60, 70, 80, 90])

print(Marks.mean(), Marks.median(), Marks.max(), Marks.min())

75.0 75.0 90 60

## Q15. Mini Practice

Create a DataFrame with:
Name, Age, Score, Height

Tasks:
1. Sort by Score (Descending)
2. Find Mean Age
3. Find Median Height
4. Show Score Frequency

In [119]:
import pandas as pd

# Create the DataFrame
df = pd.DataFrame({
    "Name":   ["Aman", "Raj", "Riya", "Sita"],
    "Age":    [20, 22, 21, 23],
    "Score":  [80, 95, 80, 85],
    "Height": [165, 170, 160, 168]
})

df

   Name  Age  Score  Height
0  Aman   20     80     165
1   Raj   22     95     170
2  Riya   21     80     160
3  Sita   23     85     168

In [123]:
df.sort_values(by='Score',ascending=False)

   Name  Age  Score  Height
1   Raj   22     95     170
3  Sita   23     85     168
0  Aman   20     80     165
2  Riya   21     80     160

In [125]:
df['Age'].mean()

21.5

In [127]:
df['Height'].median()

166.5

In [121]:
df['Score'].value_counts()

Score
80    2
95    1
85    1
Name: count, dtype: int64