
# Pandas Class 6 Assignment

## Level: Basic to Intermediate

### Instructions
- Solve all questions using Pandas.
- Write code in the blank code cell below each question.
- Print the required output.


# Q1. Display Unique Values

## Problem Statement
Create a DataFrame with a City column and display all unique cities.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
['Bhopal' 'Indore' 'Delhi']
```

In [2]:
import pandas as pd

City = pd.Series(["Bhopal", "Indore", "Bhopal", "Delhi"])

City.drop_duplicates()

0    Bhopal
1    Indore
3     Delhi
dtype: object


# Q2. Count Unique Values

## Problem Statement
Find the number of unique cities in a DataFrame.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
3
```

In [6]:
City = pd.Series(["Bhopal", "Indore", "Bhopal", "Delhi"])

City.nunique()

3


# Q3. Value Counts

## Problem Statement
Count occurrences of each city.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
Bhopal    2
Indore    1
Delhi     1
```

In [8]:
City.value_counts()

Bhopal    2
Indore    1
Delhi     1
Name: count, dtype: int64


# Q4. Group By City

## Problem Statement
Find average marks city-wise using groupby().

## Sample Input
```python
City   Marks
Bhopal 80
Bhopal 90
Delhi  70
```

## Sample Output
```python
Bhopal 85
Delhi  70
```

In [10]:
df = pd.DataFrame({
    "City": ['Bhopal','Bhopal','Delhi'],
    "Marks": [80,90,70]
})

In [16]:
a = df.groupby(by='City')
a.mean()

        Marks
City
Bhopal   85.0
Delhi    70.0


# Q5. Sort Values

## Problem Statement
Sort students by Marks in ascending order.

## Sample Output
```python
Sorted DataFrame
```

In [24]:
data = {
    "Student": ["Aman", "Riya", "Sahil", "Neha"],
    "Marks": [85, 72, 90,78]
}

df = pd.DataFrame(data)
df

  Student  Marks
0    Aman     85
1    Riya     72
2   Sahil     90
3    Neha     78

In [27]:
df.sort_values(by='Marks')

  Student  Marks
1    Riya     72
3    Neha     78
0    Aman     85
2   Sahil     90


# Q6. Sort Values Descending

## Problem Statement
Sort students by Marks in descending order.

## Sample Output
```python
Sorted DataFrame
```

In [29]:
df.sort_values(by='Marks',ascending=False)

  Student  Marks
2   Sahil     90
0    Aman     85
3    Neha     78
1    Riya     72


# Q7. Filter Records

## Problem Statement
Display students having marks greater than 75.

## Sample Output
```python
Filtered rows
```

In [33]:
df[df['Marks'] > 75]

  Student  Marks
0    Aman     85
2   Sahil     90
3    Neha     78


# Q8. Multiple Conditions

## Problem Statement
Display students whose marks are greater than 70 and age is greater than 20.

## Sample Output
```python
Filtered rows
```

In [41]:
data = {
    "Student": ["Aman", "Riya", "Sahil", "Neha"],
    "Marks": [85, 72, 90,78],
    "Age": [20,25,30,40]
}

df = pd.DataFrame(data)
df

  Student  Marks  Age
0    Aman     85   20
1    Riya     72   25
2   Sahil     90   30
3    Neha     78   40

In [51]:
df[(df['Marks'] > 75) & (df['Age'] > 20)]

  Student  Marks  Age
2   Sahil     90   30
3    Neha     78   40


# Q9. Group By Department

## Problem Statement
Create Employee and Department data and find total salary department-wise.

## Sample Output
```python
HR       50000
IT      120000
```

In [53]:
import pandas as pd

data = {
    "Employee": ["Aman", "Riya", "Sahil", "Neha", "John"],
    "Department": ["HR", "IT", "IT", "HR", "Finance"],
    "Salary": [30000, 60000, 60000, 20000, 50000],
    "City": ["Bhopal", "Delhi", "Indore", "Bhopal", "Mumbai"]
}

df = pd.DataFrame(data)

print(df)

  Employee Department  Salary    City
0     Aman         HR   30000  Bhopal
1     Riya         IT   60000   Delhi
2    Sahil         IT   60000  Indore
3     Neha         HR   20000  Bhopal
4     John    Finance   50000  Mumbai

In [61]:
df.groupby('Department')['Salary'].sum()

Department
Finance     50000
HR          50000
IT         120000
Name: Salary, dtype: int64


# Q10. Complete Practice Question

## Problem Statement
Create a DataFrame containing:
- Name
- Age
- City
- Marks

Perform:
1. Show unique cities
2. Count city frequency
3. Filter marks > 80
4. Sort by marks

## Sample Output
```python
Required Results
```

In [63]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Sahil", "Neha", "Suyog"],
    "Age":  [20, 22, 21, 23, 24],
    "City": ["Bhopal", "Indore", "Delhi", "Bhopal", "Mumbai"],
    "Marks": [75, 88, 92, 67, 81]
}

df = pd.DataFrame(data)

df

    Name  Age    City  Marks
0   Aman   20  Bhopal     75
1   Riya   22  Indore     88
2  Sahil   21   Delhi     92
3   Neha   23  Bhopal     67
4  Suyog   24  Mumbai     81

In [65]:
df['City'].drop_duplicates()

0    Bhopal
1    Indore
2     Delhi
4    Mumbai
Name: City, dtype: object

In [67]:
df['City'].value_counts()

City
Bhopal    2
Indore    1
Delhi     1
Mumbai    1
Name: count, dtype: int64

In [73]:
df[df['Marks'] > 80]

    Name  Age    City  Marks
1   Riya   22  Indore     88
2  Sahil   21   Delhi     92
4  Suyog   24  Mumbai     81

In [75]:
df.sort_values(by='Marks')

    Name  Age    City  Marks
3   Neha   23  Bhopal     67
0   Aman   20  Bhopal     75
4  Suyog   24  Mumbai     81
1   Riya   22  Indore     88
2  Sahil   21   Delhi     92